[package]
name = "rq"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
reqwest = "0.12.24"
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros"] }
serde_json = "1.0.145"
termcolor = "1.4.1"